
Coins: [AAVE, APE, APT, ARB, ARK, ATOM, AVAX, BADGER, BANANA, BCH, BIGTIME, BLUR, BLZ, BNB, BSV, BBTC, CANTO, CFX, COMP, CRV, CYBER, DOGE, DOT, DYDX, ETH, FET, FRIEND, FTM, FTT, FXS, GAS, GMX, HPOS, INJ, KAS, LDO, LINK, LOOM, LTC, MATIC, MEME, MINA, MKR, NEAR, NEO, OGN, OP, ORBS, ORDI, OX, PENDLE, kPEPE, POLYX, RDNT, REQ, RLB, RNDR, RUNE, SEI, SHIA, kSHIB, SNX, SOL, STG, STRAX, STX, SUI, TIA, TON, TRB, TRX, XRP, UNI, UNIBOT, WLD, YGG, ZEN, ZRO]
# Coins: [SOL, BNB, AVAX, SUI, XRP]
# Coins: [ETH]

Exchanges: [hyperliquid] #rabbit